# Generated by Django 5.2.4 on 2025-07-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('academic_level', models.IntegerField()),
                ('country', models.IntegerField()),
                ('avg_daily_usage_hours', models.FloatField()),
                ('most_used_platform', models.IntegerField()),
                ('affects_academic_performance', models.BooleanField()),
                ('sleep_hours_per_night', models.FloatField()),
                ('mental_health_score', models.IntegerField()),
                ('relationship_status', models.IntegerField()),
                ('conflicts_over_social_media', models.BooleanField()),
                ('addicted_score', models.IntegerField()),
            ],
        ),
    ]
