# Generated by Django 5.2.4 on 2025-07-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinput',
            name='target_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinput',
            name='target_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinput',
            name='target_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinput',
            name='target_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinput',
            name='target_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinput',
            name='target_6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinput',
            name='target_7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinput',
            name='target_8',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
