# Generated by Django 5.2.3 on 2025-07-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinput',
            name='academic_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentinput',
            name='country',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentinput',
            name='gender',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentinput',
            name='most_used_platform',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentinput',
            name='relationship_status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentinput',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
