# Generated by Django 5.2.3 on 2025-07-03 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_studentinput_academic_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinput',
            name='student_id',
        ),
    ]
